Commodity naming for BEA summary sectors
USEPA/useeior pull request #57
Opened 2020-11-17 16:35 UTC by dannyhage

2020-11-22 11:39 UTC, WesIngwersen requested changes
Thanks. See my requests for minor changes.

2020-11-22 11:39 UTC, WesIngwersen commented on inst/extdata/Crosswalk_SummaryIndustrytoCommodityName2012Schema.csv
> +23,Construction,"Commerical, residential, and industrial facilities"
We can leave this as just "Construction", just because otherwise people assume that this represents any impact that would come from the building itself and not just in the construction phase.

2020-11-22 11:39 UTC, WesIngwersen commented on inst/extdata/Crosswalk_SummaryIndustrytoCommodityName2012Schema.csv
> +5415,Computer systems design and related services,"Facilities management, computer programming and systems design"
Remove "Facilities management"

2020-11-22 11:39 UTC, WesIngwersen commented on inst/extdata/Crosswalk_SummaryIndustrytoCommodityName2012Schema.csv
> +321,Wood products,"Saw mills and wood products (e.g. plywood, veneer)"
Remove "Saw mills" which connotes the mill itself.  Just "Wood products" is fine.

2020-11-23 13:34 UTC, dannyhage commented on inst/extdata/Crosswalk_SummaryIndustrytoCommodityName2012Schema.csv
> +321,Wood products,"Saw mills and wood products (e.g. plywood, veneer)"
Updates completed.

2020-11-23 18:28 UTC, merged

2020-11-27 14:34 UTC, WesIngwersen commented
@MoLi7 FYI