Refactor IO objects in model
USEPA/useeior pull request #88
Opened 2021-02-09 02:17 UTC by MoLi7

This PR is created to show up-to-date change in the refactoring and allow discussions. Please feel free to give your comments, thanks!
@WesIngwersen @bl-young @jvendries

2021-02-09 03:10 UTC, jvendries approved these changes

2021-02-09 13:49 UTC, WesIngwersen requested changes
I see that we're still assuming model$IndustryOutput and model$CommodityOutput are still vectors in this update with data for for the IO year only.  I still think this is a limitation.

2021-02-09 13:49 UTC, WesIngwersen commented on R/LoadIOTables.R
> +    model$CommodityOutput <- rowSums(model$UseTransactions) + rowSums(model$BEA$UseFinalDemand)
I still see the  model$BEA$UseFinalDemand still in use here.  This will be a problem.  I see that model$FinalDemand is declared later...we would need to declare that before this so we can use it here.

2021-02-09 19:27 UTC, MoLi7 commented on R/LoadIOTables.R
> +    model$CommodityOutput <- rowSums(model$UseTransactions) + rowSums(model$BEA$UseFinalDemand)
> I see that we're still assuming model$IndustryOutput and model$CommodityOutput are still vectors in this update with data for for the IO year only. I still think this is a limitation.

Ah.. so you expect IndustryOutput/CommodityOutput to be a df with multiple years? But do we need them all for any specified model?

2021-02-09 19:34 UTC, MoLi7 commented on R/LoadIOTables.R
> +    model$CommodityOutput <- rowSums(model$UseTransactions) + rowSums(model$BEA$UseFinalDemand)
> I still see the model$BEA$UseFinalDemand still in use here. This will be a problem. I see that model$FinalDemand is declared later...we would need to declare that before this so we can use it here.

I think it will cause a problem if we declare `model$FinalDemand` first then pass it to derive `model$CommodityOutput`. Because if the model is an industry model, `model$FinalDemand` will be transformed from by-commodity format to by-industry format, the by-industry `model$FinalDemand` cannot be summed with `rowSums(model$UseTransactions)`, which is in by-commodity format, to get `model$CommodityOutput`.

2021-02-10 00:41 UTC, WesIngwersen commented
Let us know when you're ready for another review and if you've done any checks, please provide that evidence. thanks

2021-02-12 01:05 UTC, WesIngwersen approved these changes

2021-02-12 02:16 UTC, MoLi7 commented
@WesIngwersen I pushed the new Chi function which is related to this [Jira comment](https://epalca.atlassian.net/browse/USEEIO-893?focusedCommentId=12951) from me.

2021-02-12 02:19 UTC, MoLi7 commented
Since @WesIngwersen and @bl-young has approved this PR and @jvendries has pushed validated updates about disaggregation, I'd say the refactoring work is completed. We can merge this branch with v2-alpha to continue working on  validation tasks. Please let me know if you have different opinions, thanks!

2021-02-12 14:46 UTC, merged

2021-02-12 14:47 UTC, WesIngwersen commented
@jvendries @bl-young @MoLi7  I've merged it into v2-alpha and will resume validation testing in that branch